name: Lint & release project
on:
  push:
    paths:
      - 'fox_orm/**'
      - '.github/**'
  pull_request:
    paths:
      - 'fox_orm/**'
      - '.github/**'

jobs:
  run-linters:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
        with:
          python-version: '3.10'

      - name: Install poetry
        shell: bash
        run: |
          pip install poetry
          poetry config virtualenvs.in-project true

      - name: Load dependency cache
        id: load-cache
        uses: actions/cache@v2
        with:
          path: .venv
          key: venv-${{ runner.os }}-${{ hashFiles('**/poetry.lock') }}
      - name: Install dependencies
        run: poetry install
        if: steps.load-cache.outputs.cache-hit != 'true'

      - name: Check with black
        if: github.event_name != 'push'
        run: poetry run black -S --check --diff fox_orm
      - name: Reformat with black
        if: github.event_name == 'push'
        run: poetry run black -S fox_orm
      - name: Commit chanes
        if: github.event_name == 'push'
        shell: bash
        run: |
          if [ ! -n "$(git status --porcelain)" ]; then
            exit
          fi
          git add -A
          git config user.name "github-actions"
          git config user.email "action@github.com"
          git commit -m "style: reformat [skip ci]"
          git push

